version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: estaplit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"

