# Generated by Django 4.2.3 on 2023-10-16 05:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('place_id', models.TextField(unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('rate', models.CharField(max_length=50)),
                ('working_hours', models.JSONField(null=True)),
                ('payment_options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CREDIT_CARD', 'Cartão de Crédito'), ('DEBIT_CARD', 'Cartão de Débito'), ('PIX', 'Pix'), ('CASH', 'Dinheiro')], max_length=50), null=True, size=None)),
                ('open_parking_spot', models.IntegerField(null=True)),
                ('total_parking_spot', models.IntegerField(null=True)),
                ('open_schedule_parking_spot', models.IntegerField(null=True)),
                ('total_schedule_parking_spot', models.IntegerField(null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR')),
                ('available_schedules', models.JSONField(null=True)),
                ('price_table', models.JSONField(null=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_date_and_time', models.DateTimeField()),
                ('ticket_status', models.CharField(choices=[('APPROVED', 'Confirmada'), ('WAITING', 'Aguardando estacionamento'), ('CANCELLED', 'Cancelada')], default='WAITING', max_length=30)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('ticket_code', models.CharField(default='16102023051827', max_length=30)),
                ('driver_car', models.CharField(max_length=200)),
                ('driver_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR')),
                ('driver_name', models.CharField(max_length=200)),
                ('parking_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.parkingspace')),
            ],
        ),
    ]
