# Generated by Django 4.2.3 on 2023-10-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='ticket_code',
            field=models.CharField(default='11102023023309', max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ticket_date_and_time',
            field=models.DateTimeField(),
        ),
    ]
