# Generated by Django 4.2.6 on 2023-10-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='place_id',
            field=models.TextField(default='PLACE_ID'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ticket_code',
            field=models.CharField(default='11102023231409', max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ticket_date_and_time',
            field=models.DateTimeField(),
        ),
    ]
