# Generated by Django 4.2.6 on 2023-10-12 03:50

import django.contrib.postgres.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_parkingspace_place_id_alter_reservation_ticket_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='available_schedules',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='open_parking_spot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='open_schedule_parking_spot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='payment_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CREDIT_CARD', 'Cartão de Crédito'), ('DEBIT_CARD', 'Cartão de Débito'), ('PIX', 'Pix'), ('CASH', 'Dinheiro')], max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BR'),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='place_id',
            field=models.TextField(blank=True, default='PLACE_ID', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='price_table',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='rate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='total_parking_spot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='total_schedule_parking_spot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='working_hours',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ticket_code',
            field=models.CharField(default='12102023005056', max_length=30),
        ),
    ]
