# Generated by Django 4.2.3 on 2023-10-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_reservation_ticket_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='ticket_code',
            field=models.CharField(default='06102023042104', max_length=30),
        ),
    ]
